# Node docker image on which this would be run
image: python:3.7.3

# doe het gvd!
#This command is run before actual stages start running
before_script:
  - pip install flask
  - pip install PyMongo

stages:
  - test
  - deploy

# Job 1:
test:
  stage: test
  script:
    # - py --version
    # - py test.py
    - python --version
    - python test.py

deployToAWS:
  only:
    - master
  stage: deploy
  before_script:
    #generate ssh key
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add <(echo "$PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 600 ~/.ssh/id_rsa > ~/.ssh/authorized_keys
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./deploy/gitlab-deploy.sh